//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorevler
    {
        public int GorevNo { get; set; }
        public string Gorevler1 { get; set; }
    }
}
